// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEkT8rTRAUM4zibjXHzk7rEc_RZfTIg2c',
    appId: '1:891925302993:web:4ddfa5ddb93ac202f73ff0',
    messagingSenderId: '891925302993',
    projectId: 'cl-prototype',
    authDomain: 'cl-prototype.firebaseapp.com',
    storageBucket: 'cl-prototype.appspot.com',
    measurementId: 'G-YLC2C5PWFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEcC5QbhQf_5hzFUfRp9Mea4fNiPUYoto',
    appId: '1:891925302993:android:29b013429214e0d1f73ff0',
    messagingSenderId: '891925302993',
    projectId: 'cl-prototype',
    storageBucket: 'cl-prototype.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1Xu7vV_3NN5Cbb8i2zc22kwNSfJEi0IA',
    appId: '1:891925302993:ios:1b152488499c7297f73ff0',
    messagingSenderId: '891925302993',
    projectId: 'cl-prototype',
    storageBucket: 'cl-prototype.appspot.com',
    iosClientId: '891925302993-bblfffipqilsr8ujh5fb1c0eojbbl4p8.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1Xu7vV_3NN5Cbb8i2zc22kwNSfJEi0IA',
    appId: '1:891925302993:ios:1b152488499c7297f73ff0',
    messagingSenderId: '891925302993',
    projectId: 'cl-prototype',
    storageBucket: 'cl-prototype.appspot.com',
    iosClientId: '891925302993-bblfffipqilsr8ujh5fb1c0eojbbl4p8.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
